### PR TITLE
Changes for Feb2020 Sync

### PR DESCRIPTION
**Pull request by francescobrivio**
- Global Tags from: https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVAnalysisSummaryTable
- Different MET corrections for 2016, 2017 and 2018
-   Rerun deepFlavor for 2016 and 2017: https://twiki.cern.ch/twiki/bin/view/CMS/DeepJet#102X_installation_recipe
- Rerun deepCSV for 2016
- TES from slide 47 of: https://indico.cern.ch/event/887196/contributions/3743090/attachments/1984772/3306737/TauPOG_TES_20200210.pdf

### CODE REVIEW

**Comment by francescobrivio** [comment]
@camendola @dzuolo @davignon please review these changes

**Comment by francescobrivio** [comment]
PU jet ID is still missing, I will add it later

**Comment by francescobrivio** [comment]
Added new PU jet ID from: https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetID#9X_2017_and_10X_2018_recipes

Also updated instructions in README.md.

**Comment by francescobrivio** [comment]
I have tested everything on few events of of data and MC for all three years (2016/17/18) but please test it another time just to be sure!

**Comment by dzuolo** [comment]
Please check bTag if statements for 2016/2017

**Comment by francescobrivio** [comment]
@dzuolo thanks for spotting that ( https://github.com/LLRCMS/LLRHiggsTauTau/pull/108/commits/586c75c823d172b8ee4fa64c0505ddb0a644e008#diff-468eaad02e6398c2b33fe9959bc41666R563 ), I will fix it

**Comment by francescobrivio** [comment]
In order to have the correct PU jet IDs we switch to CMSSW_10_2_20 (on SLC6)

**Comment by francescobrivio** [comment]
TES is now taken from the TauPOG tool. I had to translate to c++ the python code implemented here:
https://github.com/cms-tau-pog/TauIDSFs/blob/master/python/TauIDSFTool.py#L164-L184

I still have to add the ele->tauh fake Energy Scale (from the same TauPOG tool)

**Comment by francescobrivio** [comment]
Fixed some minor bugs in last TES implementation and updated EES from TauPOG tool:
https://github.com/cms-tau-pog/TauIDSFs/blob/master/python/TauIDSFTool.py#L206-L242
(EES values were actually correct, but now they are read from root file instead of hard coded).

**Comment by francescobrivio** [comment]
we could also make some code clean-up in `TauFiller.cc`, for now I leave everything there

**Comment by francescobrivio** [comment]
finally added PUjetID. I had to change how we read the updated value: it is not an userFloat anymore, but we ready it through token/handle mechanism.

**Comment by francescobrivio** [comment]
@dzuolo @camendola @davignon please review and test this PR

**Pull request merged**
