### PR TITLE
Update data samples + Double muon triggers

### PR DESCRIPTION
**Pull request by bfonta**
This PR brings the most up-to-date version of our data samples. 
In parallel, I've added DoubleMuon triggers and the corresponding datasets, which will be useful for determining MET trigger scale factors. As an example, you can see the recommended DoubleMuon triggers for Run2 analysis [in this Twiki](https://twiki.cern.ch/twiki/bin/view/CMS/MuonHLT2018).

### CODE REVIEW

**Comment by portalesHEP** [comment]
looking good to me; could you also apply those updates to the 124X branch?

**Comment by dzuolo** [comment]
Thank you Bruno! Just one question: I do not see any filter in the trigger paths you added. Are they needed or not?

**Comment by dzuolo** [comment]
Additional comment: can you please add these two samples? Tobias kindly figured out that tthToTauTau now exists also for 2016(APV). Thanks!
https://cmsweb.cern.ch/das/request?input=dataset%3D%2FttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8%2FRunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2%2FMINIAODSIM&instance=prod/global

https://cmsweb.cern.ch/das/request?input=dataset%3D%2FttHToTauTau_M125_TuneCP5_13TeV-powheg-pythia8%2FRunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2%2FMINIAODSIM&instance=prod/global

**Comment by bfonta** [comment]
@dzuolo DoubleMuon will be used simply to cross-check the MET trigger scale factors derived with SingleMuon. The derivation will be very similar for both sets of triggers. Importantly, for the most part we do not care about the efficiency of single legs since we are not studying trigger efficiencies. I would then say that we do not need the filters. Thanks to @portalesHEP for discussing this in private.
Regarding the samples, I will add those as soon as possible.

**Comment by dzuolo** [comment]
> @dzuolo DoubleMuon will be used simply to cross-check the MET trigger scale factors derived with SingleMuon. The derivation will be very similar for both sets of triggers. Importantly, for the most part we do not care about the efficiency of single legs since we are not studying trigger efficiencies. I would then say that we do not need the filters. Thanks to @portalesHEP for discussing this in private.
> Regarding the samples, I will add those as soon as possible.

Ok thanks a lot for the explanation!

**Comment by bfonta** [comment]
@portalesHEP @dzuolo I believe I addressed all your comments.

**Comment by portalesHEP** [comment]
Thanks! Happy to merge, except if @dzuolo has more comment

**Comment by dzuolo** [comment]
No I'm ok thanks!

**Pull request merged**
