### PR TITLE
New CMSSW version and new L1 prefering weights

### PR DESCRIPTION
**Pull request by dzuolo**
L1 preferring new recipe described in: https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1PrefiringWeightRecipe

### CODE REVIEW

**Comment by portalesHEP** [comment]
Do I understand correctly that this new recipe only changes the way the weights are retrieved, and not the weights themselves?

**Comment by dzuolo** [comment]
> Do I understand correctly that this new recipe only changes the way the weights are retrieved, and not the weights themselves?

No the weights are actually different because a new correction to account for something in the muon detectors was added for the ultra legacy reco.

**Comment by dzuolo** [comment]
After the last fixes everything compiles and runs. Klub filter check should be fixed to properly account for the new filter.

**Comment by portalesHEP** [comment]
> > Do I understand correctly that this new recipe only changes the way the weights are retrieved, and not the weights themselves?
> 
> No the weights are actually different because a new correction to account for something in the muon detectors was added for the ultra legacy reco.

I see, judging by what is presented e.g. [here](https://indico.cern.ch/event/1037022/contributions/4371535/attachments/2253080/3822432/20210527_L1Prefiring_JSchulte.pdf), the additional correction is mostly relevant for 2016. This was the main reason for the question: do we need to reproduce the 2018 samples to account for this fix. For the prefiring alone I guess not, but since you also included the missing MET filter we probably should.

**Comment by dzuolo** [comment]
> > > Do I understand correctly that this new recipe only changes the way the weights are retrieved, and not the weights themselves?
> > 
> > 
> > No the weights are actually different because a new correction to account for something in the muon detectors was added for the ultra legacy reco.
> 
> I see, judging by what is presented e.g. [here](https://indico.cern.ch/event/1037022/contributions/4371535/attachments/2253080/3822432/20210527_L1Prefiring_JSchulte.pdf), the additional correction is mostly relevant for 2016. This was the main reason for the question: do we need to reproduce the 2018 samples to account for this fix. For the prefiring alone I guess not, but since you also included the missing MET filter we probably should.

Ahhhhh ok! I would say yes, sorry about that. I forget this filter for some reason in the past...

**Comment by portalesHEP** [comment]
I think this can be merged. Just to be sure, will you also take care of the KLUB update?

**Comment by dzuolo** [comment]
Yes I will take of the KLUB update too!

**Comment by dzuolo** [comment]
KLUB PR: https://github.com/LLRCMS/KLUBAnalysis/pull/242

**Comment by dzuolo** [comment]
@portalesHEP : If you find everything ok you can merge this PR now :)

**Comment by portalesHEP** [comment]
> KLUB PR: [LLRCMS/KLUBAnalysis#242](https://github.com/LLRCMS/KLUBAnalysis/pull/242)

Thanks for that, merging now

**Pull request merged**
