### PR TITLE
Updates for 2018 data sample analysis on branch 102 X_HH

### PR DESCRIPTION
**Pull request by dzuolo**
Updates for 2018 data sample analysis:
- added monitoring triggers (https://twiki.cern.ch/twiki/bin/view/CMS/TauTrigger)
- Added deepFlavour branches
- Updated instructions for FSR modules
- Added new TES corrections and uncertainties (https://twiki.cern.ch/twiki/bin/view/CMS/TauIDRecommendation13TeV)
- Removed reprocessing of electrons ID (default in 102X)

### CODE REVIEW

**Comment by francescobrivio** [comment]
@camendola this PR should be ok, but we still need to review it. wait before merging it!

**Comment by francescobrivio** [comment]
@dzuolo when you updated the TES you missed the uncertainty on the 3prong:
NominalTESUncertainty3Pr = cms.double(0.9) should be 0.8, please fix it

@camendola after this fix is done the PR is ok for me and can be merged

**Comment by francescobrivio** [comment]
+1 @camendola please merge this PR when you have time

**Comment by dzuolo** [comment]
@francescobrivio @camendola The value has been fixed :)

**Pull request merged**
