### PR TITLE
Added updating the 2017 PUJetId for consistency

### PR DESCRIPTION
**Pull request by kramerto**

### CODE REVIEW

**Comment by portalesHEP** [comment]
Rerunning the PUJetId training for 2017 is not necessary as far as I know; do we want to do it anyway?

**Comment by kramerto** [comment]
Sorry, I should have written a comment. I briefly discussed this with @dzuolo. The current implementation is not working for 2017, which is why I opened this PR. The alternative would be to treat 2017 specifically in several places (config/Ntuplizer). I also re-ran the pujetid for one example file and saw minor differences (probably negligible though) although they should be identical. So for the sake of simplicity (keeping as much code as possible common between the different eras) and to be on the safe side, re-running it might be the easiest choice.

**Comment by portalesHEP** [comment]
> I also re-ran the pujetid for one example file and saw minor differences (probably negligible though) 

Do you have some plots to illustrate that? It might be good to be sure of how negligible they are before deciding on the implementation

**Comment by kramerto** [comment]
image_2022_11_25T14_34_51_422Z
I ran over one file of one of the lheZpt binned DY samples. Blue is after re-running, red is before.

**Comment by portalesHEP** [comment]
> I ran over one file of one of the lheZpt binned DY samples. Blue is after re-running, red is before.

Thanks ! Indeed that does not look like it has any significant impact. I'm ok with merging if there's nothing to be added

**Comment by portalesHEP** [comment]
Double checking if anything else is to be added before merging @riga @kramerto

**Comment by kramerto** [comment]
No, I don't think so

**Pull request merged**
