### PR TITLE
Changes for UL preparation

### PR DESCRIPTION
**Pull request by dzuolo**
Changes for UL preparation.
- New lumi masks (https://twiki.cern.ch/twiki/bin/view/CMS/PdmV2018Analysis#Legacy_Re_Reco - https://twiki.cern.ch/twiki/bin/view/CMS/PdmV2017Analysis#Data - https://twiki.cern.ch/twiki/bin/view/CMS/PdmV2016Analysis#Legacy_Re_Reco)
- New Global Tags (https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2LegacyAnalysis)
- New EGamma sequence (https://twiki.cern.ch/twiki/bin/view/CMS/EgammaUL2016To2018)
- New PFJetID recipe (https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL)
- Removed unnecessary sequences from producer (MET, ecalBadCalibration MET filter, bTag algorithms, PUJetID, tauID)
- Added PUPPI MET
- Added JEC files for the three years (https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC#Jet_Energy_Corrections_in_Run2) and changed ntuplizer for 2017 and 2018
- New TES files added (https://github.com/cms-tau-pog/TauIDSFs/tree/master/data) - Use Legacy EES corrections as suggested by tauID experts
- 2016 JEC files included in ntuplizer--> Run 2016F split in two suberas in order to use correct jec files
- Fixed L1 pre-firing recipe (https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1ECALPrefiringWeightRecipe#Accessing_the_UL2017_maps)in producer. Maps to be manually downloaded until we switch to CMSSW > 10_6_26
- Modified producer to re-run MET filter "Flag_BadPFMuonDzFilter" on miniAODv1 (https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#UL_data)
- Added electrons corrected energies and resolutions in separate branches for test purposes.

To do:
- MET Filters: recommendations not final for 2016 MC, Need to include "Flag_ecalBadCalibFilter" only for 2017 and 2018

### CODE REVIEW

**Comment by dzuolo** [comment]
The last commit concludes (for the time being) the work on the new HiggsTauTauProduced_106X. 
L1 prefiring section should be reviewed once the maps for 2016 and 2017 will be available (https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1ECALPrefiringWeightRecipe#Accessing_the_UL2017_maps).

**Comment by dzuolo** [comment]
New ntuplizer tested on a 2018 MC file seems working

**Review by portalesHEP — APPROVED** [review]
Thanks a lot! I don't see anything obviously wrong in the changes and I assume you've done the necessary tests to ensure everything's working properly, so it's all good for me!

**Comment by dzuolo** [comment]
I tested the PR using four MC files from 2016 (pre- and post-VFP), 2017 and 2018. Everything seems to work properly.

**Comment by francescobrivio** [comment]
> I tested the PR using four MC files from 2016 (pre- and post-VFP), 2017 and 2018. Everything seems to work properly.

@dzuolo did you also tested it on data?

**Comment by dzuolo** [comment]
> > I tested the PR using four MC files from 2016 (pre- and post-VFP), 2017 and 2018. Everything seems to work properly.
> 
> @dzuolo did you also tested it on data?

@francescobrivio I just did it and it seems to work on data too.

**Comment by dzuolo** [comment]
I believe there is a point we should investigate: for 2016 there are two sets of MC samples but one set of data. How can we make data vs MC plots if 2016 data contains the whole luminosity but the MC only half of that? Is there something we should change here in LLR or everything should be done in KLUB?

**Comment by portalesHEP** [comment]
I'm not sure there's any issue here: 2016APV MC corresponds to periods B to F, and 2016 non APV to periods G and H; I guess we should just pay attention to that splitting (maybe just draw distributions separately for cross-checks), or am I missing something?

**Comment by dzuolo** [comment]
I also believe that there is no issue. I just wanted to be sure that processing separately RunB to RunF-HIPM and RunF-NoHIPM to RunH was the right thing to do and no other changes were required to the code.

**Comment by dzuolo** [comment]
On a different topic I would like to ask your opinion about this piece of code https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#Recipe_for_BadPFMuonDz_filter_in that I added to the producer in order to re-run the BadPFMuonDz MET filter. The recipe is quite different compared to the one for ecalBadCalibReducedMINIAODFilter that we applied to the Legacy miniAOD for the non-resonant analysis, https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#How_to_run_ecal_BadCalibReducedM. I cannot figure out if adding the first snippet of code to the producer is enough or not.

**Comment by dzuolo** [comment]
In the last commit I added the re-run of the BadPFMuonDzFilter in a similar way to what was done in the legacy framework for ecalBadCalibFilter, still waiting for a confirmation of this from the MET experts.
I added electrons scale and smearing corrections using the correct recipe, confirmed by the Egamma POG. I preferred to use separate variables in such a way that we can test the effect of these shifts in our final discriminator and decide if need them or not, as was done for the non-resonant analysis.

**Comment by dzuolo** [comment]
I consider this PR now complete. The last item of the list concerning the MET filters can be investigated later on together with other changes that may be required to implement the new triggers.

**Pull request merged**
