### PR TITLE
Electron ID for 2018 samples

### PR DESCRIPTION
**Pull request by dzuolo**
Please refer to https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2 for an explanation of the changes.
- Added 2017v2 EleID to Ntuplizer and EleFiller
- Added egammaPostRecoSeq to Producer 
- Added instruction for 2017v2 EleID to README

### CODE REVIEW

**Comment by francescobrivio** [comment]
@dzuolo in EleFiller and HTauTauNtuplizer please restore the same names that were used before, e.g. from the new "passMvaIsowp80Id" to the old "isEleID80". The implementation is correct, but for consistency it is better to keep the same names.

**Comment by francescobrivio** [comment]
@dzuolo thanks for the changes! @camendola this is fine for me, you can merge it!

**Comment by camendola** [comment]
Missing in the README:
```git cms-merge-topic cms-egamma:EgammaPostRecoTools ```
otherwise egammaPostRecoSeq doesn't work.
And
```git cms-merge-topic cms-egamma:EgammaID_1023```
is no longer necessary (https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2#2018_MiniAOD)

Did anyone try it yet? For me that merge-topic downloads a lot of (useless, I guess) cmssw repositories

**Comment by dzuolo** [comment]
Hi @camendola ,
I tried to run the framework without "git cms-merge-topic cms-egamma:EgammaPostRecoTools" and it was not working because there is this part in the producer:

from RecoEgamma.EgammaTools.EgammaPostRecoTools import setupEgammaPostRecoSeq
setupEgammaPostRecoSeq(process,
                       runEnergyCorrections=False,
                       era='2018-Prompt')

This is because we decided not to apply the energy corrections on electrons and photons but these lines are needed to have the 2017v2 Ele ID, according tho what is written in the wiki.
Davide

**Comment by camendola** [comment]
ciao @dzuolo,
aren't we saying the same thing? :) 
```git cms-merge-topic cms-egamma:EgammaPostRecoTools``` is needed and should be added in the readme (I didn't do it myself because I'm not sure if someone is working on this branch and has uncommitted stuff).

Chiara

**Comment by dzuolo** [comment]
Ciao @camendola ,
I'm sorry I made a mistake when I updated the README file:
I removed "git cms-merge-topic cms-egamma:EgammaPostRecoTools" instead of "git cms-merge-topic cms-egamma:EgammaID_1023". That's why I did'n understand your first comment: I thought that "git cms-merge-topic cms-egamma:EgammaPostRecoTools" was already there. I'll update it ASAP.
Davide

**Pull request merged**
